# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nouveau_wid.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import cryptagetexte as ct
import cle
import codage_image as ci
from PIL import Image
import numpy as np

from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QSize



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(999, 705)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 961, 681))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.CC = QtWidgets.QWidget()
        self.CC.setObjectName("CC")
        self.layoutWidget = QtWidgets.QWidget(self.CC)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 6, 931, 651))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(870, 50))
        self.label_5.setMaximumSize(QtCore.QSize(870, 50))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Blac")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(150, 30))
        self.label.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.TextInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.TextInput.setMinimumSize(QtCore.QSize(675, 30))
        self.TextInput.setMaximumSize(QtCore.QSize(675, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextInput.setFont(font)
        self.TextInput.setObjectName("TextInput")
        self.horizontalLayout_2.addWidget(self.TextInput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.CC_ModeInput = QtWidgets.QComboBox(self.layoutWidget)
        self.CC_ModeInput.setMinimumSize(QtCore.QSize(300, 30))
        self.CC_ModeInput.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CC_ModeInput.setFont(font)
        self.CC_ModeInput.setObjectName("CC_ModeInput")
        self.CC_ModeInput.addItem("")
        self.CC_ModeInput.addItem("")
        self.horizontalLayout_3.addWidget(self.CC_ModeInput)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.CC_CryptageTypeInput = QtWidgets.QComboBox(self.layoutWidget)
        self.CC_CryptageTypeInput.setMinimumSize(QtCore.QSize(300, 30))
        self.CC_CryptageTypeInput.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CC_CryptageTypeInput.setFont(font)
        self.CC_CryptageTypeInput.setObjectName("CC_CryptageTypeInput")
        self.CC_CryptageTypeInput.addItem("")
        self.CC_CryptageTypeInput.addItem("")
        self.CC_CryptageTypeInput.addItem("")
        self.horizontalLayout_4.addWidget(self.CC_CryptageTypeInput)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setEnabled(True)
        self.label_4.setMinimumSize(QtCore.QSize(150, 30))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.CC_KeyInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.CC_KeyInput.setMinimumSize(QtCore.QSize(675, 30))
        self.CC_KeyInput.setMaximumSize(QtCore.QSize(675, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CC_KeyInput.setFont(font)
        self.CC_KeyInput.setObjectName("CC_KeyInput")
        self.horizontalLayout_5.addWidget(self.CC_KeyInput)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 300))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_7.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.CC_TextOutput = QtWidgets.QLabel(self.layoutWidget)
        self.CC_TextOutput.setMinimumSize(QtCore.QSize(675, 300))
        self.CC_TextOutput.setMaximumSize(QtCore.QSize(675, 300))
        self.CC_TextOutput.setBaseSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CC_TextOutput.setFont(font)
        self.CC_TextOutput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.CC_TextOutput.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.CC_TextOutput.setAutoFillBackground(False)
        self.CC_TextOutput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CC_TextOutput.setText("")
        self.CC_TextOutput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.CC_TextOutput.setWordWrap(True)
        self.CC_TextOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.CC_TextOutput.setObjectName("CC_TextOutput")
        self.horizontalLayout_6.addWidget(self.CC_TextOutput)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ClearButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ClearButton.setMinimumSize(QtCore.QSize(0, 35))
        self.ClearButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ClearButton.setObjectName("ClearButton")
        self.horizontalLayout.addWidget(self.ClearButton)
        self.CopyButton = QtWidgets.QPushButton(self.layoutWidget)
        self.CopyButton.setMinimumSize(QtCore.QSize(200, 35))
        self.CopyButton.setMaximumSize(QtCore.QSize(200, 35))
        self.CopyButton.setObjectName("CopyButton")
        self.horizontalLayout.addWidget(self.CopyButton)
        self.OKButton = QtWidgets.QPushButton(self.layoutWidget)
        self.OKButton.setMinimumSize(QtCore.QSize(200, 35))
        self.OKButton.setMaximumSize(QtCore.QSize(200, 35))
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout.addWidget(self.OKButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.CC, "")
        self.CI = QtWidgets.QWidget()
        self.CI.setObjectName("CI")
        self.layoutWidget1 = QtWidgets.QWidget(self.CI)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 931, 621))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(870, 50))
        self.label_6.setMaximumSize(QtCore.QSize(870, 50))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Blac")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_19.addWidget(self.label_9)
        self.ModeInput_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.ModeInput_2.setMinimumSize(QtCore.QSize(300, 30))
        self.ModeInput_2.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ModeInput_2.setFont(font)
        self.ModeInput_2.setObjectName("ModeInput_2")
        self.ModeInput_2.addItem("")
        self.ModeInput_2.addItem("")
        self.horizontalLayout_19.addWidget(self.ModeInput_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_22.setMinimumSize(QtCore.QSize(0, 30))
        self.label_22.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_20.addWidget(self.label_22)
        self.ModeInput_3 = QtWidgets.QComboBox(self.layoutWidget1)
        self.ModeInput_3.setMinimumSize(QtCore.QSize(300, 30))
        self.ModeInput_3.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ModeInput_3.setFont(font)
        self.ModeInput_3.setObjectName("ModeInput_3")
        self.ModeInput_3.addItem("")
        self.ModeInput_3.addItem("")
        self.horizontalLayout_20.addWidget(self.ModeInput_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_29.setMinimumSize(QtCore.QSize(150, 30))
        self.label_29.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_21.addWidget(self.label_29)
        self.Img_CryptageInput = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Img_CryptageInput.setEnabled(True)
        self.Img_CryptageInput.setMinimumSize(QtCore.QSize(640, 30))
        self.Img_CryptageInput.setMaximumSize(QtCore.QSize(640, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Img_CryptageInput.setFont(font)
        self.Img_CryptageInput.setObjectName("Img_CryptageInput")
        self.horizontalLayout_21.addWidget(self.Img_CryptageInput)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setMinimumSize(QtCore.QSize(0, 20))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setMinimumSize(QtCore.QSize(150, 30))
        self.label_8.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_22.addWidget(self.label_8)
        self.Img_SupportImageInput = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Img_SupportImageInput.setMinimumSize(QtCore.QSize(539, 30))
        self.Img_SupportImageInput.setMaximumSize(QtCore.QSize(539, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Img_SupportImageInput.setFont(font)
        self.Img_SupportImageInput.setObjectName("Img_SupportImageInput")
        self.horizontalLayout_22.addWidget(self.Img_SupportImageInput)
        self.BrowsSupportImageButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.BrowsSupportImageButton.setMinimumSize(QtCore.QSize(93, 0))
        self.BrowsSupportImageButton.setMaximumSize(QtCore.QSize(93, 16777215))
        self.BrowsSupportImageButton.setObjectName("BrowsSupportImageButton")
        self.horizontalLayout_22.addWidget(self.BrowsSupportImageButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_31.setMinimumSize(QtCore.QSize(0, 20))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_8.addWidget(self.label_31)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setMinimumSize(QtCore.QSize(150, 30))
        self.label_12.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_23.addWidget(self.label_12)
        self.Img_SaveOutputImage = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Img_SaveOutputImage.setMinimumSize(QtCore.QSize(539, 0))
        self.Img_SaveOutputImage.setMaximumSize(QtCore.QSize(539, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Img_SaveOutputImage.setFont(font)
        self.Img_SaveOutputImage.setObjectName("Img_SaveOutputImage")
        self.horizontalLayout_23.addWidget(self.Img_SaveOutputImage)
        self.BrowsOutputImageButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.BrowsOutputImageButton.setMinimumSize(QtCore.QSize(93, 0))
        self.BrowsOutputImageButton.setMaximumSize(QtCore.QSize(93, 16777215))
        self.BrowsOutputImageButton.setObjectName("BrowsOutputImageButton")
        self.horizontalLayout_23.addWidget(self.BrowsOutputImageButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setMinimumSize(QtCore.QSize(170, 30))
        self.label_11.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_24.addWidget(self.label_11)
        self.Img_GlobalOutput = QtWidgets.QLabel(self.layoutWidget1)
        self.Img_GlobalOutput.setMinimumSize(QtCore.QSize(0, 0))
        self.Img_GlobalOutput.setMaximumSize(QtCore.QSize(675, 300))
        self.Img_GlobalOutput.setBaseSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Img_GlobalOutput.setFont(font)
        self.Img_GlobalOutput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Img_GlobalOutput.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Img_GlobalOutput.setAutoFillBackground(False)
        self.Img_GlobalOutput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Img_GlobalOutput.setText("")
        self.Img_GlobalOutput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Img_GlobalOutput.setWordWrap(True)
        self.Img_GlobalOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Img_GlobalOutput.setObjectName("Img_GlobalOutput")
        self.horizontalLayout_24.addWidget(self.Img_GlobalOutput)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CleaButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.CleaButton_2.setMinimumSize(QtCore.QSize(0, 35))
        self.CleaButton_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.CleaButton_2.setObjectName("CleaButton_2")
        self.horizontalLayout_7.addWidget(self.CleaButton_2)
        self.CopyButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.CopyButton_2.setEnabled(True)
        self.CopyButton_2.setMinimumSize(QtCore.QSize(200, 35))
        self.CopyButton_2.setMaximumSize(QtCore.QSize(200, 35))
        self.CopyButton_2.setObjectName("CopyButton_2")
        self.horizontalLayout_7.addWidget(self.CopyButton_2)
        self.OKButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.OKButton_2.setMinimumSize(QtCore.QSize(200, 35))
        self.OKButton_2.setMaximumSize(QtCore.QSize(200, 35))
        self.OKButton_2.setObjectName("OKButton_2")
        self.horizontalLayout_7.addWidget(self.OKButton_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.CI, "")
        self.RSA = QtWidgets.QWidget()
        self.RSA.setObjectName("RSA")
        self.layoutWidget2 = QtWidgets.QWidget(self.RSA)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 10, 921, 631))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setMinimumSize(QtCore.QSize(870, 50))
        self.label_13.setMaximumSize(QtCore.QSize(870, 50))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Blac")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_18.setSpacing(30)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_30.setMinimumSize(QtCore.QSize(0, 30))
        self.label_30.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_7.addWidget(self.label_30)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 30))
        self.label_14.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_16.setMinimumSize(QtCore.QSize(150, 30))
        self.label_16.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.RSA_u1_int_input = QtWidgets.QSpinBox(self.layoutWidget2)
        self.RSA_u1_int_input.setMinimumSize(QtCore.QSize(0, 25))
        self.RSA_u1_int_input.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RSA_u1_int_input.setFont(font)
        self.RSA_u1_int_input.setMinimum(2)
        self.RSA_u1_int_input.setMaximum(9)
        self.RSA_u1_int_input.setObjectName("RSA_u1_int_input")
        self.horizontalLayout_11.addWidget(self.RSA_u1_int_input)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_17.setMinimumSize(QtCore.QSize(150, 30))
        self.label_17.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.RSA_u1_privateKeyInput = QtWidgets.QSpinBox(self.layoutWidget2)
        self.RSA_u1_privateKeyInput.setMinimumSize(QtCore.QSize(0, 25))
        self.RSA_u1_privateKeyInput.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RSA_u1_privateKeyInput.setFont(font)
        self.RSA_u1_privateKeyInput.setMinimum(1)
        self.RSA_u1_privateKeyInput.setMaximum(999)
        self.RSA_u1_privateKeyInput.setObjectName("RSA_u1_privateKeyInput")
        self.horizontalLayout_12.addWidget(self.RSA_u1_privateKeyInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setMinimumSize(QtCore.QSize(170, 30))
        self.label_18.setMaximumSize(QtCore.QSize(170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.RSA_u1_SecretKeOutput = QtWidgets.QLabel(self.layoutWidget2)
        self.RSA_u1_SecretKeOutput.setMinimumSize(QtCore.QSize(270, 60))
        self.RSA_u1_SecretKeOutput.setMaximumSize(QtCore.QSize(270, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RSA_u1_SecretKeOutput.setFont(font)
        self.RSA_u1_SecretKeOutput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.RSA_u1_SecretKeOutput.setMouseTracking(False)
        self.RSA_u1_SecretKeOutput.setTabletTracking(False)
        self.RSA_u1_SecretKeOutput.setText("")
        self.RSA_u1_SecretKeOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.RSA_u1_SecretKeOutput.setObjectName("RSA_u1_SecretKeOutput")
        self.horizontalLayout_13.addWidget(self.RSA_u1_SecretKeOutput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.RSA_u1_CopyKeyButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RSA_u1_CopyKeyButton.setEnabled(True)
        self.RSA_u1_CopyKeyButton.setMinimumSize(QtCore.QSize(150, 35))
        self.RSA_u1_CopyKeyButton.setMaximumSize(QtCore.QSize(150, 35))
        self.RSA_u1_CopyKeyButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RSA_u1_CopyKeyButton.setObjectName("RSA_u1_CopyKeyButton")
        self.verticalLayout_3.addWidget(self.RSA_u1_CopyKeyButton)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setMinimumSize(QtCore.QSize(0, 30))
        self.label_15.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_20.setMinimumSize(QtCore.QSize(190, 30))
        self.label_20.setMaximumSize(QtCore.QSize(190, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.RSA_u2_PrivateKeyInput = QtWidgets.QSpinBox(self.layoutWidget2)
        self.RSA_u2_PrivateKeyInput.setMinimumSize(QtCore.QSize(180, 25))
        self.RSA_u2_PrivateKeyInput.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RSA_u2_PrivateKeyInput.setFont(font)
        self.RSA_u2_PrivateKeyInput.setMinimum(1)
        self.RSA_u2_PrivateKeyInput.setMaximum(999)
        self.RSA_u2_PrivateKeyInput.setObjectName("RSA_u2_PrivateKeyInput")
        self.horizontalLayout_17.addWidget(self.RSA_u2_PrivateKeyInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setMinimumSize(QtCore.QSize(160, 30))
        self.label_19.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.RSA_u2_SecretKeyOutput = QtWidgets.QLabel(self.layoutWidget2)
        self.RSA_u2_SecretKeyOutput.setMinimumSize(QtCore.QSize(270, 60))
        self.RSA_u2_SecretKeyOutput.setMaximumSize(QtCore.QSize(270, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RSA_u2_SecretKeyOutput.setFont(font)
        self.RSA_u2_SecretKeyOutput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.RSA_u2_SecretKeyOutput.setMouseTracking(False)
        self.RSA_u2_SecretKeyOutput.setTabletTracking(False)
        self.RSA_u2_SecretKeyOutput.setText("")
        self.RSA_u2_SecretKeyOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.RSA_u2_SecretKeyOutput.setObjectName("RSA_u2_SecretKeyOutput")
        self.horizontalLayout_16.addWidget(self.RSA_u2_SecretKeyOutput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.RSA_u2_CopyKeyButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RSA_u2_CopyKeyButton.setMinimumSize(QtCore.QSize(150, 35))
        self.RSA_u2_CopyKeyButton.setMaximumSize(QtCore.QSize(150, 35))
        self.RSA_u2_CopyKeyButton.setObjectName("RSA_u2_CopyKeyButton")
        self.verticalLayout_5.addWidget(self.RSA_u2_CopyKeyButton)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.horizontalLayout_18.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_23.setMinimumSize(QtCore.QSize(0, 30))
        self.label_23.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_24.setMinimumSize(QtCore.QSize(150, 30))
        self.label_24.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.RSA_RSA_IntInput = QtWidgets.QSpinBox(self.layoutWidget2)
        self.RSA_RSA_IntInput.setMinimumSize(QtCore.QSize(150, 25))
        self.RSA_RSA_IntInput.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RSA_RSA_IntInput.setFont(font)
        self.RSA_RSA_IntInput.setMaximum(2147483647)
        self.RSA_RSA_IntInput.setObjectName("RSA_RSA_IntInput")
        self.horizontalLayout_8.addWidget(self.RSA_RSA_IntInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_25.setMinimumSize(QtCore.QSize(150, 30))
        self.label_25.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.RSA_RSA_IntGenerateButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RSA_RSA_IntGenerateButton.setMinimumSize(QtCore.QSize(150, 30))
        self.RSA_RSA_IntGenerateButton.setMaximumSize(QtCore.QSize(150, 30))
        self.RSA_RSA_IntGenerateButton.setObjectName("RSA_RSA_IntGenerateButton")
        self.horizontalLayout_9.addWidget(self.RSA_RSA_IntGenerateButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.RSA_CreateKeyButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RSA_CreateKeyButton.setMinimumSize(QtCore.QSize(200, 40))
        self.RSA_CreateKeyButton.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RSA_CreateKeyButton.setFont(font)
        self.RSA_CreateKeyButton.setObjectName("RSA_CreateKeyButton")
        self.horizontalLayout_10.addWidget(self.RSA_CreateKeyButton)
        self.RSA_GeneralClearButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RSA_GeneralClearButton.setMinimumSize(QtCore.QSize(200, 40))
        self.RSA_GeneralClearButton.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RSA_GeneralClearButton.setFont(font)
        self.RSA_GeneralClearButton.setObjectName("RSA_GeneralClearButton")
        self.horizontalLayout_10.addWidget(self.RSA_GeneralClearButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_28.setMinimumSize(QtCore.QSize(0, 30))
        self.label_28.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_26.setMinimumSize(QtCore.QSize(100, 30))
        self.label_26.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.RSA_PublicKeyOutput = QtWidgets.QLabel(self.layoutWidget2)
        self.RSA_PublicKeyOutput.setMinimumSize(QtCore.QSize(270, 60))
        self.RSA_PublicKeyOutput.setMaximumSize(QtCore.QSize(270, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RSA_PublicKeyOutput.setFont(font)
        self.RSA_PublicKeyOutput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.RSA_PublicKeyOutput.setMouseTracking(False)
        self.RSA_PublicKeyOutput.setTabletTracking(False)
        self.RSA_PublicKeyOutput.setText("")
        self.RSA_PublicKeyOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.RSA_PublicKeyOutput.setObjectName("RSA_PublicKeyOutput")
        self.horizontalLayout_14.addWidget(self.RSA_PublicKeyOutput)
        self.RSA_PublicKeyCopyButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RSA_PublicKeyCopyButton.setMinimumSize(QtCore.QSize(60, 35))
        self.RSA_PublicKeyCopyButton.setMaximumSize(QtCore.QSize(60, 35))
        self.RSA_PublicKeyCopyButton.setObjectName("RSA_PublicKeyCopyButton")
        self.horizontalLayout_14.addWidget(self.RSA_PublicKeyCopyButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_27.setMinimumSize(QtCore.QSize(100, 30))
        self.label_27.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.RSA_PrivateKeyOutput = QtWidgets.QLabel(self.layoutWidget2)
        self.RSA_PrivateKeyOutput.setMinimumSize(QtCore.QSize(270, 60))
        self.RSA_PrivateKeyOutput.setMaximumSize(QtCore.QSize(270, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RSA_PrivateKeyOutput.setFont(font)
        self.RSA_PrivateKeyOutput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.RSA_PrivateKeyOutput.setMouseTracking(False)
        self.RSA_PrivateKeyOutput.setTabletTracking(False)
        self.RSA_PrivateKeyOutput.setText("")
        self.RSA_PrivateKeyOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.RSA_PrivateKeyOutput.setObjectName("RSA_PrivateKeyOutput")
        self.horizontalLayout_15.addWidget(self.RSA_PrivateKeyOutput)
        self.RSA_PrivateKeyCopyButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RSA_PrivateKeyCopyButton.setMinimumSize(QtCore.QSize(60, 35))
        self.RSA_PrivateKeyCopyButton.setMaximumSize(QtCore.QSize(60, 35))
        self.RSA_PrivateKeyCopyButton.setObjectName("RSA_PrivateKeyCopyButton")
        self.horizontalLayout_15.addWidget(self.RSA_PrivateKeyCopyButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_18.addLayout(self.verticalLayout_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.tabWidget.addTab(self.RSA, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Cryptages Classiques"))
        self.label.setText(_translate("Form", "Texte Entrée :"))
        self.label_2.setText(_translate("Form", "Mode :"))
        self.CC_ModeInput.setCurrentText(_translate("Form", "Cryptage"))
        self.CC_ModeInput.setItemText(0, _translate("Form", "Cryptage"))
        self.CC_ModeInput.setItemText(1, _translate("Form", "Décryptage"))
        self.label_3.setText(_translate("Form", "Type cryptage :"))
        self.CC_CryptageTypeInput.setItemText(0, _translate("Form", "César"))
        self.CC_CryptageTypeInput.setItemText(1, _translate("Form", "Vigenère"))
        self.CC_CryptageTypeInput.setItemText(2, _translate("Form", "RSA"))
        self.label_4.setText(_translate("Form", "Clé :"))
        self.label_7.setText(_translate("Form", "Texte Sortie :"))
        self.ClearButton.setText(_translate("Form", "CLEAR"))
        self.CopyButton.setText(_translate("Form", "COPIE SORTIE"))
        self.OKButton.setText(_translate("Form", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CC), _translate("Form", "Crypto Classique"))
        self.label_6.setText(_translate("Form", "Cryptage Images"))
        self.label_9.setText(_translate("Form", "Mode :"))
        self.ModeInput_2.setCurrentText(_translate("Form", "Cryptage"))
        self.ModeInput_2.setItemText(0, _translate("Form", "Cryptage"))
        self.ModeInput_2.setItemText(1, _translate("Form", "Décryptage"))
        self.label_22.setText(_translate("Form", "Mode :"))
        self.ModeInput_3.setCurrentText(_translate("Form", "Texte"))
        self.ModeInput_3.setItemText(0, _translate("Form", "Texte"))
        self.ModeInput_3.setItemText(1, _translate("Form", "Image"))
        self.label_29.setText(_translate("Form", "Entrée cryptage :"))
        self.label_21.setText(_translate("Form", "Dans le cas d\'une image (NOIR ET BLANC, format PNG uniquement), entrer le chemin d\'accès à l\'image"))
        self.label_8.setText(_translate("Form", "Entrée chemin image support :"))
        self.BrowsSupportImageButton.setText(_translate("Form", "Browse"))
        self.label_31.setText(_translate("Form", "Image PNG uniquement"))
        self.label_12.setText(_translate("Form", "Chemin enregistrement image sortie :"))
        self.BrowsOutputImageButton.setText(_translate("Form", "Browse"))
        self.label_11.setText(_translate("Form", "Sortie :"))
        self.CleaButton_2.setText(_translate("Form", "CLEAR"))
        self.CopyButton_2.setText(_translate("Form", "COPIE SORTIE"))
        self.OKButton_2.setText(_translate("Form", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CI), _translate("Form", "Cryptage Images"))
        self.label_13.setText(_translate("Form", "Clés"))
        self.label_30.setText(_translate("Form", "Diffie-Hellman"))
        self.label_14.setText(_translate("Form", "User 1"))
        self.label_16.setText(_translate("Form", "Entrez un entier :"))
        self.label_17.setText(_translate("Form", "Entrez votre clé privée :"))
        self.label_18.setText(_translate("Form", "Clé secrète partagée :"))
        self.RSA_u1_CopyKeyButton.setText(_translate("Form", "COPIE CLE"))
        self.label_15.setText(_translate("Form", "User 2"))
        self.label_20.setText(_translate("Form", "Entrez votre clé privée :"))
        self.label_19.setText(_translate("Form", "Clé secrète partagée :"))
        self.RSA_u2_CopyKeyButton.setText(_translate("Form", "COPIE CLE"))
        self.label_23.setText(_translate("Form", "RSA"))
        self.label_24.setText(_translate("Form", "Entrez un entier au hasard :"))
        self.label_25.setText(_translate("Form", "Choix automatique :"))
        self.RSA_RSA_IntGenerateButton.setText(_translate("Form", "GENERER"))
        self.RSA_CreateKeyButton.setText(_translate("Form", "GENERER CLE"))
        self.RSA_GeneralClearButton.setText(_translate("Form", "GENERAL CLEAR"))
        self.label_28.setText(_translate("Form", "SORTIE"))
        self.label_26.setText(_translate("Form", "Clé Publique :"))
        self.RSA_PublicKeyCopyButton.setText(_translate("Form", "COPIER"))
        self.label_27.setText(_translate("Form", "Clé privée :"))
        self.RSA_PrivateKeyCopyButton.setText(_translate("Form", "COPIER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RSA), _translate("Form", "Cryptage RSA"))

##Page 1 - cryptage Classiques

    def copie_cc(self): 
        """copie le texte de sortie de cryptage classe dans le presse papier"""
        clipboard = QtGui.QGuiApplication.clipboard()
        clipboard.setText(self.CC_TextOutput.text())

    def clear_cc(self):
        """clear la page cryptage classiques"""
        self.TextInput.setText('')
        self.CC_KeyInput.setText('')
        self.CC_TextOutput.setText('')
        self.CC_ModeInput.setCurrentIndex(0)
        self.CC_CryptageTypeInput.setCurrentIndex(0)

    def main_cryptoClassique(self):
        """permet de lancer la bonne fonction suivant le type de codage"""
        if self.CC_CryptageTypeInput.currentIndex()==0:
            self.cesar_vigenere(True)
        if self.CC_CryptageTypeInput.currentIndex()==1:
            self.cesar_vigenere(False)
        else:
            self.rsa()

    def cesar_vigenere(self, pos):
        """crypte ou décrypte en césar. si pos=True : cesar, sinon : vigenere"""
        mail=ct.Message(self.TextInput.text())
        if self.CC_ModeInput.currentIndex() == 1:
            mail.modecryptage('off')
        key=cle.Clé(self.CC_KeyInput.text())
        if pos:
            try:
                mail.cesar(key)
            except(Exception):
                self.CC_TextOutput.setText('##ERROR KEY : Key must be int type')
        else:
            try:
                mail.vigenere(key)
            except(Exception):
                self.CC_TextOutput.setText('##ERROR KEY : Key must be string type')
        self.CC_TextOutput.setText(str(mail.texte))
        
    def rsa(self):
        """crypte ou décrypte en RSA"""
        self.CC_TextOutput.setText('##CRYPTAGE RSA INDISPONIBLE')


##Page 2 - cryptage images

    def copie_ci(self): 
        """copie le texte de sortie de cryptage images dans le presse papier"""
        try:
            clipboard = QtGui.QGuiApplication.clipboard()
            clipboard.setText(self.Img_GlobalOutput.text())
        except(Exception):
            self.Img_GlobalOutput.setText('##ERREUR COPIE')

    def clear_ci(self):
        """clear la page cryptage images"""
        self.ModeInput_2.setCurrentIndex(0)
        self.ModeInput_3.setCurrentIndex(0)
        self.Img_CryptageInput.setText('')
        self.Img_SupportImageInput.setText('')
        self.Img_SaveOutputImage.setText('')
        self.Img_GlobalOutput.setText('')

    def cryptageimages(self):
        """description"""
        if self.ModeInput_3.currentIndex() == 1: #si l'entrée est une image
            if self.ModeInput_2.currentIndex() == 0: #si on veut cacher l'image dans l'image
                mon_image = Image.open(self.Img_CryptageInput.text())
                Mat = np.array(mon_image)
                mon_image2 = Image.open(self.Img_SupportImageInput.text())
                Mat2 = np.array(mon_image2)
                camoufimg = ci.pictureinpicture(Mat2,Mat)
                if self.Img_SaveOutputImage.text() == '':
                    self.Img_GlobalOutput.setPixmap(QPixmap(camoufimg.camouflage_image()).scaled(QSize(100,100)))
                else:
                    self.Img_GlobalOutput.setPixmap(QPixmap(camoufimg.camouflage_image(self.Img_SaveOutputImage.text())).scaled(QSize(100,100)))
            else: #si on veut cacher un texte dans une image
                mon_image = Image.open(self.Img_SupportImageInput.text())
                mat = np.array(mon_image)
                revelimg = ci.pictureinpicture(mat,np.zeros(5))
                self.Img_GlobalOutput.setPixmap(QPixmap(revelimg.extraction_image(self.Img_SaveOutputImage.text()))).scaled(QSize(100,100))
        
        else: #si l'entrée est un texte
            if self.ModeInput_2.currentIndex() == 1: #mode revelation
                mon_image = Image.open(self.Img_SupportImageInput.text())
                Mat = np.array(mon_image)
                revelimg = ci.texteinpicture('',Mat)
                self.Img_GlobalOutput.setPixmap(QPixmap(revelimg.extraction())).scaled(QSize(100,100))
                #probleme enregistrement image

            else:
                mon_image = Image.open(self.Img_SupportImageInput.text())
                Mat = np.array(mon_image)
                cachimg = ci.texteinpicture(self.Img_CryptageInput.text(),Mat)
                self.Img_GlobalOutput.setPixmap(QPixmap(cachimg.camouflage(self.Img_SaveOutputImage.text()))).scaled(QSize(100,100))


##Page 3 - Clés

    def copie_keyu1(self):
        """copie la clé secrete de user 1"""
        clipboard = QtGui.QGuiApplication.clipboard()
        clipboard.setText(self.RSA_u1_SecretKeOutput.text())

    def copie_keyu2(self):
        """copie la clé secrete de user 1"""
        clipboard = QtGui.QGuiApplication.clipboard()
        clipboard.setText(self.RSA_u2_SecretKeyOutput.text())

    def copie_publicexit(self):
        """copie la clé puclique (sortie)"""
        clipboard = QtGui.QGuiApplication.clipboard()
        clipboard.setText(self.RSA_PublicKeyOutput.text())

    def copie_privateexit(self):
        """copie la clé puclique (sortie)"""
        clipboard = QtGui.QGuiApplication.clipboard()
        clipboard.setText(self.RSA_PrivateKeyOutput.text())

    def clear_cles(self):
        """clear la page Clés"""
        self.RSA_u1_int_input.setValue(2)
        self.RSA_u1_privateKeyInput.setValue(1)
        self.RSA_u1_SecretKeOutput.setText('')
        self.RSA_u2_PrivateKeyInput.setValue(1)
        self.RSA_u2_SecretKeyOutput.setText('')
        self.RSA_RSA_IntInput.setValue(0) #à voir avec Anto
        self.RSA_PublicKeyOutput.setText('')
        self.RSA_PrivateKeyOutput.setText('')

    def int_alt(self):
        """renvoie un entier au hasard"""
        self.RSA_RSA_IntInput.setValue(int(cle.entierhasard('328000000.txt')))


    def diffielman(self):
        """gère les clés de Diffie Helman"""
        g=int(self.RSA_u1_int_input.value())
        a=int(self.RSA_u1_privateKeyInput.value())
        #A=g**a
        b=int(self.RSA_u2_PrivateKeyInput.value())
        #B=g**b
        self.RSA_u1_SecretKeOutput.setText(str(g**a**b))
        self.RSA_u2_SecretKeyOutput.setText(str(g**a**b))

    def clersa(self):
        """gère les clés RSA"""
        public,private=cle.RSA('328000000.txt',self.RSA_RSA_IntInput.value())
        self.RSA_PublicKeyOutput.setText(public.texte)
        self.RSA_PrivateKeyOutput.setText(private.texte)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    #Page 1
    ui.CopyButton.clicked.connect(lambda : ui.copie_cc())
    ui.ClearButton.clicked.connect(lambda : ui.clear_cc())

    #Page 2
    ui.CopyButton_2.clicked.connect(lambda : ui.copie_ci())
    ui.CleaButton_2.clicked.connect(lambda : ui.clear_ci())

    #Page 3
    ui.RSA_u1_CopyKeyButton.clicked.connect(lambda : ui.copie_keyu1())
    ui.RSA_u2_CopyKeyButton.clicked.connect(lambda : ui.copie_keyu2())
    ui.RSA_PublicKeyCopyButton.clicked.connect(lambda : ui.copie_publicexit())
    ui.RSA_PrivateKeyCopyButton.clicked.connect(lambda : ui.copie_privateexit())
    ui.RSA_GeneralClearButton.clicked.connect(lambda : ui.clear_cles())
    ui.OKButton.clicked.connect(lambda : ui.main_cryptoClassique())
    ui.RSA_RSA_IntGenerateButton.clicked.connect(lambda : ui.int_alt())
    ui.RSA_CreateKeyButton.clicked.connect(lambda : ui.diffielman())
    ui.RSA_CreateKeyButton.clicked.connect(lambda : ui.clersa())

    sys.exit(app.exec_())
