# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wid_vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(422, 332)
        Form.setMinimumSize(QtCore.QSize(422, 332))
        Form.setMaximumSize(QtCore.QSize(422, 332))
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(60, 20, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova Cond")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 55, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 80, 386, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(11)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.horizontalLayout.addWidget(self.label2)
        self.ModeInput = QtWidgets.QComboBox(self.layoutWidget)
        self.ModeInput.setMinimumSize(QtCore.QSize(200, 30))
        self.ModeInput.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.ModeInput.setFont(font)
        self.ModeInput.setEditable(False)
        self.ModeInput.setObjectName("ModeInput")
        self.ModeInput.addItem("")
        self.ModeInput.addItem("")
        self.horizontalLayout.addWidget(self.ModeInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(11)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.horizontalLayout_2.addWidget(self.label3)
        self.TextInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.TextInput.setMinimumSize(QtCore.QSize(200, 30))
        self.TextInput.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.TextInput.setFont(font)
        self.TextInput.setObjectName("TextInput")
        self.horizontalLayout_2.addWidget(self.TextInput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(11)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.horizontalLayout_3.addWidget(self.label4)
        self.KeyInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.KeyInput.setMinimumSize(QtCore.QSize(200, 30))
        self.KeyInput.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.KeyInput.setFont(font)
        self.KeyInput.setObjectName("KeyInput")
        self.horizontalLayout_3.addWidget(self.KeyInput)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(11)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.horizontalLayout_4.addWidget(self.label5)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(200, 30))
        self.textBrowser.setMaximumSize(QtCore.QSize(200, 30))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_4.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 280, 381, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ButtonClear = QtWidgets.QPushButton(self.layoutWidget1)
        self.ButtonClear.setMinimumSize(QtCore.QSize(100, 30))
        self.ButtonClear.setMaximumSize(QtCore.QSize(100, 30))
        self.ButtonClear.setObjectName("ButtonClear")
        self.horizontalLayout_5.addWidget(self.ButtonClear)
        self.OKButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.OKButton.setMinimumSize(QtCore.QSize(100, 30))
        self.OKButton.setMaximumSize(QtCore.QSize(100, 30))
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_5.addWidget(self.OKButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cryptage Vigenère"))
        self.label1.setText(_translate("Form", "Cryptage Vigenère"))
        self.label2.setText(_translate("Form", "Mode :"))
        self.ModeInput.setCurrentText(_translate("Form", "Cryptage"))
        self.ModeInput.setItemText(0, _translate("Form", "Cryptage"))
        self.ModeInput.setItemText(1, _translate("Form", "Décryptage"))
        self.label3.setText(_translate("Form", "Texte entrée :"))
        self.label4.setText(_translate("Form", "Clé de cryptage :"))
        self.label5.setText(_translate("Form", "Texte sortie :"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ButtonClear.setText(_translate("Form", "CLEAR"))
        self.OKButton.setText(_translate("Form", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
